#!/usr/bin/env python3
"""Turn assets/AUCOOP_logotip.png into half-block cell data for lib/logo.sh.

Each terminal cell holds two vertical pixels. A pixel is 0 (empty),
1 (black in the logo, drawn light on a dark terminal) or 2 (AUCOOP blue).
A cell is stored as one digit: top * 3 + bottom.

Usage: python3 lib/make-logo.py > lib/logo.sh
"""
from pathlib import Path
from PIL import Image

SRC = Path(__file__).resolve().parent.parent / "assets" / "AUCOOP_logotip.png"


def cells(width):
    im = Image.open(SRC).convert("RGBA")
    sw, sh = im.size
    height = round(sh / sw * width)
    height += height % 2
    px = im.load()

    def pixel(x0, y0, x1, y1):
        dark = blue = n = 0
        for y in range(int(y0), max(int(y0) + 1, int(y1))):
            for x in range(int(x0), max(int(x0) + 1, int(x1))):
                r, g, b, a = px[min(x, sw - 1), min(y, sh - 1)]
                n += 1
                if a < 128:
                    continue
                if b > 150 and g > 100:
                    blue += 1
                else:
                    dark += 1
        if (dark + blue) / n < 0.45:
            return 0
        return 2 if blue >= dark else 1

    grid = [[pixel(x * sw / width, y * sh / height, (x + 1) * sw / width, (y + 1) * sh / height)
             for x in range(width)] for y in range(height)]
    used = [x for x in range(width) if any(row[x] for row in grid)]
    first, last = used[0], used[-1] + 1
    return ["".join(str(grid[y][x] * 3 + grid[y + 1][x]) for x in range(first, last))
            for y in range(0, height, 2)]


def main():
    print("# shellcheck shell=bash")
    print("# Generated by lib/make-logo.py from assets/AUCOOP_logotip.png. Do not edit.")
    for name, width in (("LOGO_BIG", 70), ("LOGO_SMALL", 44)):
        print(f"{name}=(")
        for row in cells(width):
            print(f"  '{row}'")
        print(")")


if __name__ == "__main__":
    main()
